In [2]:
import numpy as np
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [8]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [9]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [10]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [12]:
for i in np.nditer(arr12):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [5]:
#Indexing using Boolean array
arr12[arr12>9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [7]:
arr12[(arr12>5) & (arr12%2!=0)]

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23])

In [8]:
arr12[(arr12>5) & (arr12%2!=0)]=0

In [9]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  0],
       [ 8,  0, 10,  0],
       [12,  0, 14,  0],
       [16,  0, 18,  0],
       [20,  0, 22,  0]])

In [ ]:
arr12