In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [2]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [3]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [4]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [5]:
arr1>3

array([False, False, False,  True,  True,  True])

In [2]:
arr3=np.arange (6).reshape (2,3)
arr4=np.arange(6,12).reshape (3,2)

In [7]:
arr3.dot (arr4)

array([[ 28,  31],
       [100, 112]])

In [3]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [11]:
arr1*=arr2

In [12]:
arr1

array([ 4, 10, 18, 28, 40, 54])

In [13]:
arr4.min()

np.int64(6)

In [15]:
print(arr4.min())

6


In [16]:
arr4.min(axis=0)

array([6, 7])

In [17]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [18]:
arr4.sum()

np.int64(51)

In [19]:
arr4.sum(axis=0)

array([24, 27])

In [20]:
arr4.sum(axis=1)

array([13, 17, 21])

In [21]:
arr4. mean ()

np.float64(8.5)

In [22]:
arr4. mean (axis=0)

array([8., 9.])

In [23]:
arr4.mean(axis=1)

array([ 6.5,  8.5, 10.5])

In [24]:
arr4.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [25]:
arr4.std()

np.float64(1.707825127659933)

In [26]:
np.median (arr4)

np.float64(8.5)

In [27]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])