In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [2]:
arr3=np.arange (6).reshape (2,3)
arr4=np.arange(6,12).reshape (3,2)

In [3]:
for i in np.nditer(arr4):
    print(i,end=" ")

6 7 8 9 10 11 

In [4]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [5]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
for i in arr4.ravel():
    print(i, end=" ")

6 7 8 9 10 11 

In [7]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
arr4.reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
arr5=np. arange(12,18) . reshape(2,3)

In [11]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [12]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
np. hstack( (arr3, arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [14]:
np. vstack( (arr3, arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [15]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [16]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]